### ISSUE TITLE
`gradlew server` fails on Windows 10 (works on Ubuntu)

### ISSUE THREAD

**Issue by nedtwigg** [silksmith/sample-app#1]
Here's the output on Windows 10.

```
cmd> gradlew :design:silksmith:server
:design:silksmith:ensureExtractedArtifacts
:design:silksmith:sassGems
NoMethodError: undefined method `map' for nil:NilClass
  install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:174
  install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/dependency_installer.rb:404
    <top> at <script>:1
                                                                                                                       :design:silksmith:sassGems                                                                                              FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':design:silksmith:sassGems'.
> (NoMethodError) undefined method `map' for nil:NilClass

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.995 secs
```

**Comment by mxab** [comment]
ok strange, I can make a new release later with some updated dependencies including a new jruby version and hope it fixes this issue

**Comment by nedtwigg** [comment]
In case this helps:

```
cmd> gradlew server --stacktrace
:ensureExtractedArtifacts
:sassGems
NoMethodError: undefined method `map' for nil:NilClass
  install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:174
  install at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/dependency_installer.rb:404
    <top> at <script>:1
                                                                                                                       :sassGems                                                                                                               FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sassGems'.
> (NoMethodError) undefined method `map' for nil:NilClass

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':sassGems'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
        at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `map' for nil:NilClass
        at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:131)
        at org.jruby.embed.ScriptingContainer.runUnit(ScriptingContainer.java:1311)
        at org.jruby.embed.ScriptingContainer.runScriptlet(ScriptingContainer.java:1304)
        at io.silksmith.css.sass.task.GemInstallTask$_install_closure1.doCall(GemInstallTask.groovy:47)
        at io.silksmith.css.sass.task.GemInstallTask.install(GemInstallTask.groovy:42)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 69 more
Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `map' for nil:NilClass
        at RUBY.install(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/request_set.rb:174)
        at RUBY.install(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/dependency_installer.rb:404)
        at RUBY.<top>(<script>:1)
```

**Comment by mxab** [comment]
Hi @nedtwigg 

I fixed this issue, it is currently in the snapshot

if you want to give it a try use

```
repositories {
    maven {
      url = "https://oss.jfrog.org/oss-snapshot-local"
    }
    mavenCentral()
}
dependencies {
    classpath "io.silksmith:plugin:0.7.0-SNAPSHOT"
 }
}
apply plugin : "io.silksmith.plugin"
```

instead of

```
plugins {
  id "io.silksmith.plugin" version "0.6.2"
}
```

**Comment by nedtwigg** [comment]
At first I got some errors, but after deleting the repo and trying again (dirty build folder perhaps?)  I can confirm that it works, and the server starts.  But as soon as I point Chrome at it, I get another error:

```
cmd> gradlew server
:ensureExtractedArtifacts
:sassGems
installing gems into C:\Users\ntwigg\Downloads\sample-app-master\.gems\sassGems
:server
Started Development Server at http://192.168.56.1:10101/
//192.168.56.1:10101/FILES/module/io.silksmith.libs/closure-base/1.0.2+smith.0/statics/C:Userstwigg.silksmithepoio.silksmith.libsclosure-base%01.0.2+smith.0staticsclosuregoog%08ase.js
org.gradle.api.UncheckedIOException: Could not normalize path for file 'C:\Users\ntwigg\.silksmith\repo\io.silksmith.libs\closure-base\1.0.2+smith.0\statics\C:Userstwigg.silksmithepoio.silksmith.libsclosure-base.0.2+smith.0staticsclosuregooase.js'.
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:141)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:83)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:63)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
        at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:616)
        at org.gradle.api.Project$file$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at io.silksmith.development.server.files.FilesHandler.handle(FilesHandler.groovy:71)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
        at java.io.File.getCanonicalPath(File.java:618)
        at java.io.File.getCanonicalFile(File.java:643)
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:98)
        ... 22 more
//192.168.56.1:10101/FILES/module/io.silksmith.libs/jquery/1.11.2+smith.0/statics/C:Userstwigg.silksmithepoio.silksmith.libsjquery%01.11.2+smith.0staticsjquery.min.js
org.gradle.api.UncheckedIOException: Could not normalize path for file 'C:\Users\ntwigg\.silksmith\repo\io.silksmith.libs\jquery\1.11.2+smith.0\statics\C:Userstwigg.silksmithepoio.silksmith.libsjquery.11.2+smith.0staticsjquery.min.js'.
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:141)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:83)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:63)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
        at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:616)
        at org.gradle.api.Project$file$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at io.silksmith.development.server.files.FilesHandler.handle(FilesHandler.groovy:71)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
        at java.io.File.getCanonicalPath(File.java:618)
        at java.io.File.getCanonicalFile(File.java:643)
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:98)
        ... 22 more
> Building 66% > :server
```

**Comment by nedtwigg** [comment]
Before deleting the refasterjs folder:

```
cmd> gradlew server
init proxyHandler's servlethandler
init proxyHandler

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'todo-sample'.
> Expected directory 'C:\Users\ntwigg/.silksmith/repo/io.silksmith.libs/closure-base/v20150604/statics' to contain exactly one file, however, it contains no files.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

After deleting the refasterjs folder, the server opens.  But as in the other issue, I can't open the server.

```
cmd> gradlew server
init proxyHandler's servlethandler
init proxyHandler
:ensureExtractedArtifacts
:sassGems
installing gems into C:\Users\ntwigg\Downloads\silksmith-todo-sample-master\.gems\sassGems
:server
In closure task ':server'
Started Development Server at http://192.168.56.1:10101/
//192.168.56.1:10101/FILES/module/io.silksmith.libs/closure-base/v20150604/statics/C:Userstwigg.silksmithepoio.silksmith.libsclosure-base%0B20150604staticsclosuregoog%08ase.js
org.gradle.api.UncheckedIOException: Could not normalize path for file 'C:\Users\ntwigg\.silksmith\repo\io.silksmith.libs\closure-base\v20150604\statics\C:Userstwigg.silksmithepoio.silksmith.libsclosure-base20150604staticsclosuregooase.js'.
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:141)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:83)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:63)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
        at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:616)
        at org.gradle.api.internal.file.FileOperations$file.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at io.silksmith.development.server.files.FilesHandler.handle(FilesHandler.groovy:71)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
        at java.io.File.getCanonicalPath(File.java:618)
        at java.io.File.getCanonicalFile(File.java:643)
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:98)
        ... 22 more
//192.168.56.1:10101/FILES/module/io.silksmith.libs/jquery/1.11.2+smith.0/statics/C:Userstwigg.silksmithepoio.silksmith.libsjquery%01.11.2+smith.0staticsjquery.min.js
org.gradle.api.UncheckedIOException: Could not normalize path for file 'C:\Users\ntwigg\.silksmith\repo\io.silksmith.libs\jquery\1.11.2+smith.0\statics\C:Userstwigg.silksmithepoio.silksmith.libsjquery.11.2+smith.0staticsjquery.min.js'.
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:141)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:83)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:63)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:72)
        at org.gradle.api.internal.project.AbstractProject.file(AbstractProject.java:616)
        at org.gradle.api.internal.file.FileOperations$file.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at io.silksmith.development.server.files.FilesHandler.handle(FilesHandler.groovy:71)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
        at java.io.File.getCanonicalPath(File.java:618)
        at java.io.File.getCanonicalFile(File.java:643)
        at org.gradle.api.internal.file.AbstractFileResolver.normalise(AbstractFileResolver.java:98)
        ... 22 more
> Building 66% > :server
```

**Comment by mxab** [comment]
hi @nedtwigg can you retry with the latest snapshot

```
./gradlew server --refresh-depedencies
```

**Comment by nedtwigg** [comment]
The server starts:

```
cmd> gradlew server --refresh-dependencies
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
:ensureExtractedArtifacts
:sassGems
installing gems into C:\Users\ntwigg\Downloads\sample-app-master\sample-app-master\.gems\sassGems
realtive gems into .gems/sassGems
:server
Started Development Server at http://192.168.56.1:10101/
> Building 66% > :server
```

And the webpage loads.   But if I try to use the webpage (by typing `eggs` into the textbox and pressing `Add`, then I don't get any errors at the console, but my browser shows me this:

```
HTTP ERROR: 404

Problem accessing /. Reason:

    Not Found
Powered by Jetty:// 9.3.7.v20160115
```

**Comment by mxab** [comment]
hmmm in the todo app you mean? this is strange. On my win10/ie11 virtual box this seems to works, if this happens this would actually mean something is broken in the JavaScript, is there anything in the developer console?

**Comment by nedtwigg** [comment]
I thought it was just the regular sample-app, but maybe I had it backwards.  I deleted my silksmith experiment folder, and I'm not good enough with the web frontend stuff to konw the difference between a bug in my understanding and a bug in the repo.  Thanks for all your help, best of luck with silksmith, hope the bugs I reported were more helpful than extra work :)

**Comment by mxab** [comment]
Sure they helped thanks for your feedback
